package shreyashirday;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig busDaoConfig;

    private final BusDao busDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        busDaoConfig = daoConfigMap.get(BusDao.class).clone();
        busDaoConfig.initIdentityScope(type);

        busDao = new BusDao(busDaoConfig, this);

        registerDao(Bus.class, busDao);
    }
    
    public void clear() {
        busDaoConfig.getIdentityScope().clear();
    }

    public BusDao getBusDao() {
        return busDao;
    }

}
